server:
  port: 8989
  tomcat:
    max-swallow-size: 100MB


spring:
  servlet:
    # 文件上传配置
    multipart:
      max-file-size: 1MB
      max-request-size: 5MB
      resolve-lazily: true

  # MySQL & Druid连接池
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource

    druid:
      url: jdbc:mysql://localhost:3306/zanke_blog?allowMultiQueries=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: password

      #初始化时建立物理连接的个数
      initial-size: 5
      #连接池的最小空闲数量
      min-idle: 5
      #连接池最大连接数量
      max-active: 20
      #获取连接时最大等待时间，单位毫秒
      max-wait: 60000
      #申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true
      #既作为检测的间隔时间又作为testWhileIdle执行的依据
      time-between-eviction-runs-millis: 60000
      #销毁线程时检测当前连接的最后活动时间和当前时间差大于该值时，关闭当前连接(配置连接在池中的最小生存时间)
      min-eviction-idle-time-millis: 30000
      #用来检测数据库连接是否有效的sql必须是一个査询语句(oracle中为 select1 from dual)
      validation-query: select 1
      #申请连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-borrow: false
      #归还连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-return: false
      #是否缓存preparedstatement，也就是PSCache,Pscache对支持游标的数据库性能提升巨大，比如说oracle,在mysql下建议关闭。
      pool-prepared-statements: false
      #要启用PSCache，必须配置大于0，当大于0时，pooLPreparedStatements自动触发修改为true
      max-pool-prepared-statement-per-connection-size: 1
      #合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true


  # Redis单机
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
      password: password
      timeout: 3000ms
      lettuce:
        shutdown-timeout: 3000ms
        pool:
          max-active: 8
          max-wait: 30ms
          max-idle: 8
          min-idle: 0



# MyBatis
mybatis:
  # 配置mapper文件位置
  mapper-locations: classpath:/mapper/*.xml
  # 配置实体类包名(给实体类起别名)
  type-aliases-package: com.zanke.pojo.entity, com.zanke.pojo.vo
  configuration:
    # 开启驼峰命名自动映射
    map-underscore-to-camel-case: true
    # resultMap除<id>主键外，自动映射
    auto-mapping-behavior: full
    # 配置日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# PageHelper
pagehelper:
  # 设置方言，此处指定 MySQL 数据库
  helper-dialect: mysql
  # 是否启动合理化，默认是 false。
  # 启用合理化时，如果pageNum<1会查询第一页，如果pageNum>pages（最大页数）会查询最后一页。
  # 禁用合理化时，如果pageNum<1或pageNum>pages会返回空数据
  reasonable: false
  # 是否支持接口参数来传递分页参数，默认false
  support-methods-arguments: true
  # 为了支持startPage(Object params)方法，增加了该参数来配置参数映射，用于从对象中根据属性名取值
  params: count=countSql
  # 默认值为 false，当该参数设置为 true 时，如果 pageSize=0 或者 RowBounds.limit = 0 就会查询出全部的结果（相当于没有执行分页查询，但是返回结果仍然是 Page 类型）
  page-size-zero: false


# 配置oss存储相关参数
zanke:
  oss:
    accessKey: accessKey
    secretKey: secretKey
    bucket: zanke-blog
    domainName: domainName
    maxSize: 1048576 # 1M